# Generated by Django 4.2.10 on 2024-02-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('price', models.IntegerField(default='null')),
                ('category', models.CharField(default='null', max_length=50)),
                ('types', models.CharField(default='null', max_length=50)),
                ('brand', models.CharField(default='null', max_length=50)),
                ('size', models.CharField(default='null', max_length=50)),
                ('color', models.CharField(default='null', max_length=50)),
                ('image', models.ImageField(default='null', max_length=50, upload_to='media/')),
            ],
        ),
    ]
